Khulnasoft/pr action (#41)
* latest release

* latest release

* readyapi add

* readyapi add

* 🚚 Rename GitHub links from khulnasoft/pr-assistant to khulnasoft/pr-action

diff --git a/.github/workflows/code_coverage.yaml b/.github/workflows/code_coverage.yaml
--- a/.github/workflows/code_coverage.yaml
+++ b/.github/workflows/code_coverage.yaml
@@ -1,9 +1,10 @@
 name: Code-coverage
 
 on:
-  push:
-    branches:
-      - main
+  workflow_dispatch:
+  # push:
+  #   branches:
+  #     - main
   pull_request:
     branches:
       - main
@@ -28,7 +29,7 @@ jobs:
           file: ./docker/Dockerfile
           push: false
           load: true
-          tags: khulnasoft/pr-assistant:test
+          tags: khulnasoft/pr-action:test
           cache-from: type=gha,scope=dev
           cache-to: type=gha,mode=max,scope=dev
           target: test
@@ -36,11 +37,18 @@ jobs:
       - id: code_cov
         name: Test dev docker
         run: |
-          docker run --rm khulnasoft/pr-assistant:test pytest tests/unittest --cov=pr_assistant
+          docker run --name test_container khulnasoft/pr-action:test  pytest  tests/unittest --cov=pr_action --cov-report term --cov-report xml:coverage.xml 
+          docker cp test_container:/app/coverage.xml coverage.xml
+          docker rm test_container
+
+
+      - name: Validate coverage report
+        run: |
+          if [ ! -f coverage.xml ]; then
+            echo "Coverage report not found"
+            exit 1
+          fi
       - name: Upload coverage to Codecov
         uses: codecov/codecov-action@v4.0.1
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
-          flags: unittests
-          name: code-coverage
-          fail_ci_if_error: true
